"""initial revision

Revision ID: 0edd33433450
Revises: 
Create Date: 2025-09-24 12:57:58.239114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0edd33433450'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reagents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('run_duration', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('reagent_id', sa.Integer(), nullable=True),
    sa.Column('event_start_date', sa.String(length=255), nullable=False),
    sa.Column('event_end_date', sa.String(length=255), nullable=False),
    sa.Column('time_start', sa.String(length=255), nullable=True),
    sa.Column('time_end', sa.String(length=255), nullable=True),
    sa.Column('is_there_time', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['reagent_id'], ['reagents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('reagents')
    op.drop_table('instruments')
    op.drop_table('event_types')
    # ### end Alembic commands ###
